TARGET= lrz
SRCS=lrz.c error.c getopt.c long-options.c timing.c xstrtol.c xstrtoul.c zperr.c zm.c rbsb.c zreadline.c lsyslog.c canit.c crctab.c protname.c getopt1.c vasprintf.c


include $(SRCDIR)/mk/prog.mk
