#
# Automatically generated file. Don't edit
#
LOADER_BASE=0x03000000
KERNEL_BASE=0x02000000
DRIVER_BASE=AUTODETECT
SYSPAGE_BASE=0x03002000
BOOTIMG_BASE=0x08002000
CFLAGS+= -mcpu=arm7tdmi -mtune=arm7tdmi
CONFIG_HZ=100
CONFIG_TIME_SLICE=100
CONFIG_OPEN_MAX=8
CONFIG_BUF_CACHE=8
CONFIG_FS_THREADS=1
CONFIG_ROMBOOT=y
CONFIG_BOOTDISK=y
CONFIG_KEYBOARD=y
CONFIG_CONSOLE=y
CONFIG_KEYPAD=y
CONFIG_RAMDISK=y
CONFIG_TTY=y
CONFIG_PM=y
CONFIG_PM_PERFORMANCE=y
CONFIG_DIAG_SCREEN=y
CONFIG_DEVFS=y
CONFIG_RAMFS=y
CONFIG_ARFS=y
CONFIG_ELF=y

CONFIG_CMDBOX=y
CONFIG_CMD_CAT=y
CONFIG_CMD_CLEAR=y
CONFIG_CMD_CP=y
CONFIG_CMD_DATE=y
CONFIG_CMD_DMESG=y
CONFIG_CMD_ECHO=y
CONFIG_CMD_FREE=y
CONFIG_CMD_HEAD=y
CONFIG_CMD_HOSTNAME=y
CONFIG_CMD_KILL=y
CONFIG_CMD_LS=y
CONFIG_CMD_MKDIR=y
CONFIG_CMD_MOUNT=y
CONFIG_CMD_MV=y
CONFIG_CMD_NICE=y
CONFIG_CMD_PS=y
CONFIG_CMD_PWD=y
CONFIG_CMD_REBOOT=y
CONFIG_CMD_RM=y
CONFIG_CMD_RMDIR=y
CONFIG_CMD_SH=y
CONFIG_CMD_SHUTDOWN=y
CONFIG_CMD_SLEEP=y
CONFIG_CMD_SYNC=y
CONFIG_CMD_TEST=y
CONFIG_CMD_TOUCH=y
CONFIG_CMD_UMOUNT=y
CONFIG_CMD_UNAME=y

DRIVER+= $(SRCDIR)/dev/dev.ko
BOOTTASKS+= $(SRCDIR)/usr/server/boot/boot
BOOTTASKS+= $(SRCDIR)/usr/server/proc/proc
BOOTTASKS+= $(SRCDIR)/usr/server/fs/fs
BOOTTASKS+= $(SRCDIR)/usr/server/exec/exec
BOOTFILES+= $(SRCDIR)/usr/bin/init/init
BOOTFILES+= $(SRCDIR)/usr/bin/cmdbox/cmdbox
BOOTFILES+= $(SRCDIR)/doc/LICENSE
BOOTFILES+= $(SRCDIR)/usr/sample/hello/hello

SRCDIR=/home/niels/src/prex-0.8.1
ARCH=arm
PLATFORM=gba
PROFILE=gba
CROSS_COMPILE=/usr/local/arm/bin/arm-elf-

CONFIG_CFLAGS+= -fno-stack-protector
