/*
 * Automatically generated file. Don't edit
 */
#define AUTODETECT 0
#define LOADER_BASE 0x00010000
#define KERNEL_BASE 0x80080000
#define DRIVER_BASE AUTODETECT
#define SYSPAGE_BASE 0x80000000
#define BOOTIMG_BASE 0x80012000
#define CONFIG_HZ 1000
#define CONFIG_TIME_SLICE 50
#define CONFIG_OPEN_MAX 16
#define CONFIG_BUF_CACHE 32
#define CONFIG_FS_THREADS 4
#define CONFIG_DIAG_SERIAL y
#define CONFIG_DEVFS y

#define CONFIG_CMDBOX y
#define CONFIG_CMD_CAT y
#define CONFIG_CMD_CLEAR y
#define CONFIG_CMD_CP y
#define CONFIG_CMD_DATE y
#define CONFIG_CMD_DMESG y
#define CONFIG_CMD_ECHO y
#define CONFIG_CMD_FREE y
#define CONFIG_CMD_HEAD y
#define CONFIG_CMD_HOSTNAME y
#define CONFIG_CMD_KILL y
#define CONFIG_CMD_LS y
#define CONFIG_CMD_MKDIR y
#define CONFIG_CMD_MOUNT y
#define CONFIG_CMD_MV y
#define CONFIG_CMD_NICE y
#define CONFIG_CMD_PS y
#define CONFIG_CMD_PWD y
#define CONFIG_CMD_REBOOT y
#define CONFIG_CMD_RM y
#define CONFIG_CMD_RMDIR y
#define CONFIG_CMD_SH y
#define CONFIG_CMD_SHUTDOWN y
#define CONFIG_CMD_SLEEP y
#define CONFIG_CMD_SYNC y
#define CONFIG_CMD_TEST y
#define CONFIG_CMD_TOUCH y
#define CONFIG_CMD_UMOUNT y
#define CONFIG_CMD_UNAME y

